export class Ec2CustomerGateway {}
export class Ec2DHCPOptions {}
export class Ec2EC2Fleet {}
export class Ec2EgressOnlyInternetGateway {}
export class Ec2EIP {}
export class Ec2EIPAssociation {}
export class Ec2FlowLog {}
export class Ec2Host {}
export class Ec2Instance {}
export class Ec2InternetGateway {}
export class Ec2LaunchTemplate {}
export class Ec2NatGateway {}
export class Ec2NetworkAcl {}
export class Ec2NetworkAclEntry {}
export class Ec2NetworkInterface {}
export class Ec2NetworkInterfaceAttachment {}
export class Ec2NetworkInterfacePermission {}
export class Ec2PlacementGroup {}
export class Ec2Route {}
export class Ec2RouteTable {}
export class Ec2SecurityGroup {}
export class Ec2SecurityGroupEgress {}
export class Ec2SecurityGroupIngress {}
export class Ec2SpotFleet {}
export class Ec2Subnet {}
export class Ec2SubnetCidrBlock {}
export class Ec2SubnetNetworkAclAssociation {}
export class Ec2SubnetRouteTableAssociation {}
export class Ec2TransitGateway {}
export class Ec2TransitGatewayAttachment {}
export class Ec2TransitGatewayRoute {}
export class Ec2TransitGatewayRouteTable {}
export class Ec2TransitGatewayRouteTableAssociation {}
export class Ec2TransitGatewayRouteTablePropagation {}
export class Ec2Volume {}
export class Ec2VolumeAttachment {}
export class Ec2VPC {}
export class Ec2VPCCidrBlock {}
export class Ec2VPCDHCPOptionsAssociation {}
export class Ec2VPCEndpoint {}
export class Ec2VPCEndpointConnectionNotification {}
export class Ec2VPCEndpointService {}
export class Ec2VPCEndpointServicePermissions {}
export class Ec2VPCGatewayAttachment {}
export class Ec2VPCPeeringConnection {}
export class Ec2VPNConnection {}
export class Ec2VPNConnectionRoute {}
export class Ec2VPNGateway {}
export class Ec2VPNGatewayRoutePropagation {}
