// import apiGatewayTests from './apiGateway.test'
// import appSyncTests from './apiGateway.test'
// import awsBatchTests from './apiGateway.test'
// import awsCloud9Tests from './apiGateway.test'
// import cloudformationTests from './apiGateway.test'
// import codeCommitTests from './apiGateway.test'
// import dynamoDBTests from './apiGateway.test'
// import elastiCacheTests from './apiGateway.test'
// import kinesisTests from './apiGateway.test'
// import lambdaTests from './apiGateway.test'
// import route53Tests from './apiGateway.test'
// import s3Tests from './apiGateway.test'
// import secretsManagerTests from './apiGateway.test'
// import snsTests from './apiGateway.test'
// import sqsTests from './apiGateway.test'

import './apiGateway.test'
import './appSync.test'
import './awsBatch.test'
import './awsCloud9.test'
import './cloudFront.test'
import './codeCommit.test'
import './dynamoDB.test'
import './elastiCache.test'
import './kinesis.test'
import './lambda.test'
import './route53.test'
import './s3.test'
import './secretsManager.test'
import './sns.test'
import './sqs.test'
